version: '3.8'

services:
  museum:
    image: ghcr.io/ente-io/server:latest
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ENTE_CREDENTIALS_FILE: /credentials.yaml
    configs:
      - source: credentials_yaml
        target: /credentials.yaml
    volumes:
      - ./museum.yaml:/museum.yaml:ro
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: ente_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ente_db -U pguser"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "3200:3200"
      - "3201:3201"
    environment:
      MINIO_ROOT_USER: changeme
      MINIO_ROOT_PASSWORD: changeme1234
      COOLIFY_URL: ${COOLIFY_URL:-}
      COOLIFY_FQDN: ${COOLIFY_FQDN:-}
    command: server /data --address ":3200" --console-address ":3201"
    volumes:
      - minio-data:/data
    restart: unless-stopped
    labels:
      # Labels para o Coolify detectar o serviço
      - "coolify.managed=true"
      - "coolify.type=application"
      
      # Labels do Caddy para SSL automático usando variáveis
      - "caddy_0=${COOLIFY_URL:-https://minio.localhost}"
      - "caddy_0.reverse_proxy={{upstreams 3201}}"
      - "caddy_0.header=-Server"
      - "caddy_0.encode=zstd gzip"
      
      # Labels do Traefik (caso o Coolify use ambos)
      - "traefik.enable=true"
      - "traefik.http.middlewares.minio-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.minio-gzip.compress=true"
      - "traefik.http.routers.minio-http.rule=Host(`${COOLIFY_FQDN:-minio.localhost}`)"
      - "traefik.http.routers.minio-http.entrypoints=web"
      - "traefik.http.routers.minio-http.middlewares=minio-redirect"
      - "traefik.http.routers.minio-https.rule=Host(`${COOLIFY_FQDN:-minio.localhost}`)"
      - "traefik.http.routers.minio-https.entrypoints=websecure"
      - "traefik.http.routers.minio-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.minio-https.middlewares=minio-gzip"
      - "traefik.http.services.minio.loadbalancer.server.port=3201"

configs:
  credentials_yaml:
    content: |
      db:
          host: postgres
          port: 5432
          name: ente_db
          user: pguser
          password: pgpass

      s3:
          are_local_buckets: true
          b2-eu-cen:
              key: changeme
              secret: changeme1234
              endpoint: minio:3200
              region: eu-central-2
              bucket: b2-eu-cen
          wasabi-eu-central-2-v3:
              key: changeme
              secret: changeme1234
              endpoint: minio:3200
              region: eu-central-2
              bucket: wasabi-eu-central-2-v3
              compliance: false
          scw-eu-fr-v3:
              key: changeme
              secret: changeme1234
              endpoint: minio:3200
              region: eu-central-2
              bucket: scw-eu-fr-v3

volumes:
  postgres-data:
  minio-data:
