version: '3.8'

services:
  museum:
    image: ghcr.io/ente-io/server:latest
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_admin_pass
      POSTGRES_DB: ${POSTGRES_DB}
      ENTE_DB_USER: ${POSTGRES_USER}
      ENTE_DB_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "3200:3200"
      - "3201:3201"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      COOLIFY_URL: ${COOLIFY_URL:-}
      COOLIFY_FQDN: ${COOLIFY_FQDN:-}
    command: server /data --address ":3200" --console-address ":3201"
    volumes:
      - minio-data:/data
    restart: unless-stopped
    labels:
      # Deixar o Coolify gerenciar automaticamente
      - "coolify.managed=true"
      - "coolify.type=application"


volumes:
  postgres-data:
  minio-data:
