version: '3.8'

services:
  museum:
    image: ghcr.io/ente-io/server:latest
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ENTE_CREDENTIALS_FILE: /credentials.yaml
    configs:
      - source: credentials_yaml
        target: /credentials.yaml
    volumes:
      - ./museum.yaml:/museum.yaml:ro
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    ports:
      - "3200:3200"
      - "3201:3201"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      COOLIFY_URL: ${COOLIFY_URL:-}
      COOLIFY_FQDN: ${COOLIFY_FQDN:-}
    command: server /data --address ":3200" --console-address ":3201"
    volumes:
      - minio-data:/data
    restart: unless-stopped
    labels:
      # Deixar o Coolify gerenciar automaticamente
      - "coolify.managed=true"
      - "coolify.type=application"

configs:
  credentials_yaml:
    content: |
      db:
          host: postgres
          port: 5432
          name: ${POSTGRES_DB}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}

      s3:
          are_local_buckets: true
          b2-eu-cen:
              key: ${MINIO_ROOT_USER}
              secret: ${MINIO_ROOT_PASSWORD}
              endpoint: minio:3200
              region: eu-central-2
              bucket: b2-eu-cen
          wasabi-eu-central-2-v3:
              key: ${MINIO_ROOT_USER}
              secret: ${MINIO_ROOT_PASSWORD}
              endpoint: minio:3200
              region: eu-central-2
              bucket: wasabi-eu-central-2-v3
              compliance: false
          scw-eu-fr-v3:
              key: ${MINIO_ROOT_USER}
              secret: ${MINIO_ROOT_PASSWORD}
              endpoint: minio:3200
              region: eu-central-2
              bucket: scw-eu-fr-v3

volumes:
  postgres-data:
  minio-data:
