# Ente Museum Server Configuration for Production
# This file will be mounted into the museum container

# Logging configuration for production
log-file: /var/logs/museum.log

# HTTP configuration for production
http:
  # TLS will be handled by the reverse proxy (Coolify/Traefik)
  use-tls: false

# App base endpoints - configured via environment variables
apps:
  public-albums: https://albums.vm.lucasdesenv.com
  cast: https://cast.vm.lucasdesenv.com
  accounts: https://accounts.vm.lucasdesenv.com
  family: https://app.vm.lucasdesenv.com

# Database configuration - will be overridden by environment variables
db:
  host: postgres
  port: 5432
  name: ente
  sslmode: disable
  user: postgres
  password: postgres

# S3 Configuration for local MinIO
s3:
  # Enable local bucket mode for MinIO
  are_local_buckets: true
  
  # Use path-style URLs for MinIO compatibility
  use_path_style_urls: true
  
  # Hot storage configuration
  hot_storage:
    primary: b2-eu-cen
    secondary: wasabi-eu-central-2-v3
  
  # Bucket configurations
  b2-eu-cen:
    key: minioadmin
    secret: minioadmin
    endpoint: localhost:3200
    region: eu-central-2
    bucket: b2-eu-cen
  
  wasabi-eu-central-2-v3:
    key: minioadmin
    secret: minioadmin
    endpoint: localhost:3200
    region: eu-central-2
    bucket: wasabi-eu-central-2-v3
    compliance: false
  
  scw-eu-fr-v3:
    key: minioadmin
    secret: minioadmin
    endpoint: localhost:3200
    region: eu-central-2
    bucket: scw-eu-fr-v3

# Encryption keys - will be overridden by environment variables
key:
  encryption: placeholder_encryption_key_32char
  hash: placeholder_hash_key_32char_here

# JWT configuration
jwt:
  secret: placeholder_jwt_secret_key_32char

# WebAuthn configuration for 2FA (optional)
webauthn:
  rpid: vm.lucasdesenv.com
  rporigins:
    - https://app.vm.lucasdesenv.com

# Internal configuration
internal:
  # Set to false for production to enable notifications
  silent: false
  
  # Admin configuration
  admins: []
  
  # Allow user registration (set to true to disable)
  disable-registration: false

# SMTP configuration (optional - configure if you want email notifications)
# smtp:
#   host: ${SMTP_HOST}
#   port: ${SMTP_PORT}
#   username: ${SMTP_USERNAME}
#   password: ${SMTP_PASSWORD}
#   email: ${SMTP_FROM_EMAIL}

# Replication configuration (disabled by default for self-hosting)
replication:
  enabled: false

# Background jobs configuration
jobs:
  cron:
    skip: false
  remove-unreported-objects:
    worker-count: 1
  clear-orphan-objects:
    enabled: false
