# Ente Museum Server Configuration for Production
# This file will be mounted into the museum container

# Logging configuration for production
log-file: /var/logs/museum.log

# HTTP configuration for production
http:
  # TLS will be handled by the reverse proxy (Coolify/Traefik)
  use-tls: false

# App base endpoints - these will be set via environment variables in Coolify
apps:
  public-albums: ${ENTE_ALBUMS_ORIGIN}
  cast: ${ENTE_CAST_ORIGIN}
  accounts: ${ENTE_ACCOUNTS_ORIGIN}
  family: ${ENTE_FAMILY_ORIGIN}

# Database configuration - credentials loaded from credentials.yaml
db:
  host: postgres
  port: 5432
  name: ${POSTGRES_DB}
  sslmode: disable
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

# S3 Configuration for local MinIO
s3:
  # Enable local bucket mode for MinIO
  are_local_buckets: true
  
  # Use path-style URLs for MinIO compatibility
  use_path_style_urls: true
  
  # Hot storage configuration
  hot_storage:
    primary: b2-eu-cen
    secondary: wasabi-eu-central-2-v3
  
  # Bucket configurations
  b2-eu-cen:
    key: ${MINIO_ROOT_USER}
    secret: ${MINIO_ROOT_PASSWORD}
    endpoint: localhost:3200
    region: eu-central-2
    bucket: b2-eu-cen
  
  wasabi-eu-central-2-v3:
    key: ${MINIO_ROOT_USER}
    secret: ${MINIO_ROOT_PASSWORD}
    endpoint: localhost:3200
    region: eu-central-2
    bucket: wasabi-eu-central-2-v3
    compliance: false
  
  scw-eu-fr-v3:
    key: ${MINIO_ROOT_USER}
    secret: ${MINIO_ROOT_PASSWORD}
    endpoint: localhost:3200
    region: eu-central-2
    bucket: scw-eu-fr-v3

# Encryption keys - will be generated and stored in credentials.yaml
key:
  encryption: ${MUSEUM_ENCRYPTION_KEY}
  hash: ${MUSEUM_HASH_KEY}

# JWT configuration
jwt:
  secret: ${MUSEUM_JWT_SECRET}

# WebAuthn configuration for 2FA (optional)
webauthn:
  rpid: ${WEBAUTHN_RPID}
  rporigins:
    - ${ENTE_ACCOUNTS_ORIGIN}

# Internal configuration
internal:
  # Set to false for production to enable notifications
  silent: false
  
  # Admin configuration
  admins: []
  
  # Allow user registration (set to true to disable)
  disable-registration: false

# SMTP configuration (optional - configure if you want email notifications)
# smtp:
#   host: ${SMTP_HOST}
#   port: ${SMTP_PORT}
#   username: ${SMTP_USERNAME}
#   password: ${SMTP_PASSWORD}
#   email: ${SMTP_FROM_EMAIL}

# Replication configuration (disabled by default for self-hosting)
replication:
  enabled: false

# Background jobs configuration
jobs:
  cron:
    skip: false
  remove-unreported-objects:
    worker-count: 1
  clear-orphan-objects:
    enabled: false
